const pr = 'I_18_'

export const I_18 = {
  LOAD_TRANSLATE_SAGA: `${pr}LOAD_TRANSLATE_SAGA`,
  SET_LANGUAGES_FILE_DATA: `${pr}SET_LANGUAGES_FILE_DATA`,
  SET_LANGUAGE: `${pr}SET_LANGUAGE`,
  SET_AVAIBLE_LANGUAGES: `${pr}SET_AVAIBLE_LANGUAGES`,
}