const pr = 'MAIN_CONFIG_'

export const MAIN_CONFIG = {
  SET_AUTH_CHECKING_TIME: `${pr}SET_AUTH_CHECKING_TIME`,
  SET_CONFIG_MQTT: `${pr}SET_CONFIG_MQTT`,
  SET_CONFIG_PAGE_SIZE: `${pr}SET_CONFIG_PAGE_SIZE`,
  SET_HISTORY_TIME: `${pr}SET_HISTORY_TIME`,
  SET_HISTORY_TIME_RESOLUTION: `${pr}SET_HISTORY_TIME_RESOLUTION`,
  SET_SESSION_RESUME_MAX_TIME: `${pr}SET_SESSION_RESUME_MAX_TIME`,
  SET_DEVELOPER_MODE: `${pr}SET_DEVELOPER_MODE`,
  SET_SERVER_CONFIG_SAGA: `${pr}SET_SERVER_CONFIG_SAGA`,
  SET_SERVER_CONFIG: `${pr}SET_SERVER_CONFIG`,
  SET_DEVICE_LIVE_TIME: `${pr}SET_DEVICE_LIVE_TIME`,
  SET_MASTER_MODE: `${pr}SET_MASTER_MODE`,
  SET_EXTERNAL_TOOLS: `${pr}SET_EXTERNAL_TOOLS`,
  SET_NETWORK_ATTACK_AVAILABLE: `${pr}SET_NETWORK_ATTACK_AVAILABLE`,

  SET_VERSION: `${pr}SET_VERSION`,
  SET_COMMITHASH: `${pr}SET_COMMITHASH`,
  SET_BRANCH: `${pr}SET_BRANCH`
}
